import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#181b23',
        sidebar: '#141720',
        surface: '#22252d',
        'surface-high': '#2a2e38',
        'surface-low': '#1d2029',
        'surface-lowest': '#0f1117',
        border: '#2a2e38',
        'border-strong': '#374151',
        text: '#ffffff',
        'text-body': '#d1d5db',
        'text-muted': '#9ca3af',
        'text-disabled': '#6b7280',
        primary: '#3b82f6',
        'primary-hover': '#2563eb',
        'primary-dim': '#1e3a5f',
        success: '#34d399',
        'success-dim': '#052e25',
        warning: '#fbbf24',
        'warning-dim': '#3a2a05',
        danger: '#f87171',
        'danger-dim': '#3b1111',
        info: '#93c5fd',
        'info-dim': '#1e3a5f',
        'tag-pro': '#8b5cf6',
        'tag-hot': '#ef4444',
        'tag-free': '#3b82f6',
        'tag-updated': '#a855f7',
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 3px rgba(0, 0, 0, 0.30)',
        DEFAULT: '0 4px 12px rgba(0, 0, 0, 0.35)',
        lg: '0 8px 24px rgba(0, 0, 0, 0.40)',
        xl: '0 16px 40px rgba(0, 0, 0, 0.45)',
        'glow-primary': '0 0 14px rgba(59, 130, 246, 0.35)',
        'glow-success': '0 0 10px rgba(52, 211, 153, 0.45)',
      },
      spacing: {
        sidebar: '256px',
        topbar: '62px',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
      },
      fontSize: {
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'heading-l': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'heading-m': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-s': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-l': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-m': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-s': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        label: ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        caption: ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        micro: ['9px', { lineHeight: '12px', letterSpacing: '0.12em', fontWeight: '800' }],
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
} satisfies Config
