import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#101415',
        surface: '#101415',
        'surface-dim': '#101415',
        'surface-bright': '#363a3b',
        'surface-container-lowest': '#0b0f10',
        'surface-container-low': '#191c1e',
        'surface-container': '#1d2022',
        'surface-container-high': '#272a2c',
        'surface-container-highest': '#323537',
        'on-surface': '#e0e3e5',
        'on-surface-variant': '#c2c6d4',
        'on-background': '#e0e3e5',
        'inverse-surface': '#e0e3e5',
        'inverse-on-surface': '#2d3133',
        outline: '#8c909e',
        'outline-variant': '#424752',
        'surface-tint': '#acc7ff',
        primary: '#acc7ff',
        'on-primary': '#002f67',
        'primary-container': '#0056b3',
        'on-primary-container': '#bbd0ff',
        'inverse-primary': '#115cb9',
        secondary: '#4ae176',
        'on-secondary': '#003915',
        'secondary-container': '#00b954',
        'on-secondary-container': '#004119',
        tertiary: '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#7d4e00',
        'on-tertiary-container': '#ffc57f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#acc7ff',
        'on-primary-fixed': '#001a40',
        'on-primary-fixed-variant': '#004491',
        'secondary-fixed': '#6bff8f',
        'secondary-fixed-dim': '#4ae176',
        'on-secondary-fixed': '#002109',
        'on-secondary-fixed-variant': '#005321',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-variant': '#323537',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        unit: '4px',
        'stack-sm': '8px',
        'margin-desktop': '40px',
        'container-max-width': '1200px',
        'stack-lg': '32px',
        'stack-md': '16px',
        gutter: '24px',
      },
      fontFamily: {
        headline: ['Hanken Grotesk', 'Inter', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
} satisfies Config
